[project]
name = "advent-of-code-25"
version = "0.1.0"
description = "Solutions for Advent of Code 2025."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]
